name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-app:${{ github.sha }} .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Run tests
      run: docker run my-app:${{ github.sha }} npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Packages
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/my-app
          docker tag my-app:${{ github.sha }} $IMAGE_ID:${{ github.sha }}
          docker push $IMAGE_ID:${{ github.sha }}
